# Site settings
author: Pablo Menz
title: getting ready for Programming 
header-img: img/home-bg.png
email: p.menz.r@gmail.com
copyright_name: Pablo Menz
description: > # this means to ignore newlines until "baseurl:"
  Hello world!
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  pmenz

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
